selenium_wd_hw
xGroZn/TAF_AQA18_onl pull request #2
Opened 2022-12-11 20:35 UTC by xGroZn

2022-12-13 10:51 UTC, wildpioneer requested changes

2022-12-13 10:51 UTC, wildpioneer commented on src/test/java/tests/HomeworkSmokeTest.java
> +    public void validateLaminateCalculatorTest() throws InterruptedException{
Это дополнительное задание со звездочкой, а основное где?

2022-12-13 10:51 UTC, wildpioneer commented on src/test/java/tests/HomeworkSmokeTest.java
> +        driver.findElement(By.id("ln_room_id")).sendKeys(Keys.CONTROL + "a");
После выделения надо удалить, в противном случае просто добавляется значение

2022-12-13 20:04 UTC, xGroZn commented on src/test/java/tests/HomeworkSmokeTest.java
> +    public void validateLaminateCalculatorTest() throws InterruptedException{
Добавил основное, проверьте пожалуйста.

2022-12-13 20:04 UTC, xGroZn commented on src/test/java/tests/HomeworkSmokeTest.java
> +        driver.findElement(By.id("ln_room_id")).sendKeys(Keys.CONTROL + "a");
Исправил.

2022-12-20 15:04 UTC, wildpioneer commented
Проверено

2022-12-20 15:04 UTC, closed without merging