advancedActions_hw
xGroZn/TAF_AQA18_onl pull request #5
Opened 2023-01-12 21:30 UTC by xGroZn

2023-01-16 19:10 UTC, wildpioneer requested changes

2023-01-16 19:10 UTC, wildpioneer commented on src/test/java/tests/DynamicControlsTest.java
> +        WebElement checkbox = driver.findElement(By.xpath("//input[@type='checkbox']"));
Почему waitsService.waitForElementInvisible не использовать здесь сразу?

2023-01-16 19:10 UTC, wildpioneer commented on src/test/java/tests/DynamicControlsTest.java
> +        if (!input.isEnabled()){
А это зачем?

2023-01-16 19:10 UTC, wildpioneer commented on src/test/java/tests/FileUploadTest.java
> +        String pathToFile = FileUploadTest.class.getClassLoader().getResource("witcher.jpg").getPath().substring(1);
substring(1); - будет проблема на Mac и Linux

2023-01-23 19:59 UTC, xGroZn commented on src/test/java/tests/DynamicControlsTest.java
> +        WebElement checkbox = driver.findElement(By.xpath("//input[@type='checkbox']"));
Исправил все замечания, проверьте пожалуйста

2023-01-30 19:08 UTC, wildpioneer commented
Проверено

2023-01-30 19:08 UTC, closed without merging